//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Articulos
    {
        public short IdArticulo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public string IdObjetoG { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
