//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Acciones
    {
        public CA_Acciones()
        {
            this.DE_AccionesPermisos = new HashSet<DE_AccionesPermisos>();
        }
    
        public short IdAccion { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<DE_AccionesPermisos> DE_AccionesPermisos { get; set; }
    }
}
