//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Botones
    {
        public short IdBoton { get; set; }
        public string Nombre { get; set; }
        public string clase { get; set; }
        public string iconClass { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> habilitado { get; set; }
    }
}
