//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Grupos
    {
        public CA_Grupos()
        {
            this.DE_OpcionesGrupos = new HashSet<DE_OpcionesGrupos>();
        }
    
        public short IdGrupo { get; set; }
        public Nullable<short> IdGrupoPadre { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<DE_OpcionesGrupos> DE_OpcionesGrupos { get; set; }
    }
}
