//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Opciones
    {
        public CA_Opciones()
        {
            this.DE_Permisos = new HashSet<DE_Permisos>();
            this.DE_OpcionesGrupos = new HashSet<DE_OpcionesGrupos>();
        }
    
        public short IdOpcion { get; set; }
        public Nullable<short> IdOpcionP { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public string Sistema { get; set; }
        public string Descripcion { get; set; }
        public bool Barra { get; set; }
        public short BarraPadre { get; set; }
        public bool Menu { get; set; }
        public short MenuPadre { get; set; }
        public Nullable<short> SubMenuWidth { get; set; }
        public Nullable<bool> Mostrar { get; set; }
        public Nullable<short> Orden { get; set; }
        public Nullable<int> usuAct { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual ICollection<DE_Permisos> DE_Permisos { get; set; }
        public virtual ICollection<DE_OpcionesGrupos> DE_OpcionesGrupos { get; set; }
    }
}
