//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Personas
    {
        public CA_Personas()
        {
            this.CA_Personas1 = new HashSet<CA_Personas>();
        }
    
        public int IdPersona { get; set; }
        public Nullable<int> IdRepresentanteLegal { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
        public Nullable<bool> PersonaFisica { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<byte> IdPais { get; set; }
        public Nullable<byte> IdEstado { get; set; }
        public Nullable<short> IdMunicipio { get; set; }
        public Nullable<short> IdLocalidad { get; set; }
        public Nullable<short> IdColonia { get; set; }
        public Nullable<short> IdCalle { get; set; }
        public string NumeroExt { get; set; }
        public string NumeroInt { get; set; }
        public string CP { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
    
        public virtual Ca_Calles Ca_Calles { get; set; }
        public virtual Ca_Colonias Ca_Colonias { get; set; }
        public virtual ICollection<CA_Personas> CA_Personas1 { get; set; }
        public virtual CA_Personas CA_Personas2 { get; set; }
    }
}
