//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Perfiles
    {
        public CA_Perfiles()
        {
            this.CA_Usuarios = new HashSet<CA_Usuarios>();
            this.DE_Permisos = new HashSet<DE_Permisos>();
            this.DE_AccionesPermisos = new HashSet<DE_AccionesPermisos>();
        }
    
        public byte IdPerfil { get; set; }
        public string Descripcion { get; set; }
        public string DefaultPage { get; set; }
        public Nullable<int> usuAct { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual ICollection<CA_Usuarios> CA_Usuarios { get; set; }
        public virtual ICollection<DE_Permisos> DE_Permisos { get; set; }
        public virtual ICollection<DE_AccionesPermisos> DE_AccionesPermisos { get; set; }
    }
}
