//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlGeneralContainer : DbContext
    {
        public ControlGeneralContainer()
            : base("name=ControlGeneralContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CA_Acciones> CA_Acciones { get; set; }
        public DbSet<CA_Articulos> CA_Articulos { get; set; }
        public DbSet<CA_Botones> CA_Botones { get; set; }
        public DbSet<Ca_Calles> Ca_Calles { get; set; }
        public DbSet<CA_CamarasComercio> CA_CamarasComercio { get; set; }
        public DbSet<Ca_ClasificacionArticulos> Ca_ClasificacionArticulos { get; set; }
        public DbSet<Ca_Colonias> Ca_Colonias { get; set; }
        public DbSet<Ca_Estados> Ca_Estados { get; set; }
        public DbSet<Ca_Localidades> Ca_Localidades { get; set; }
        public DbSet<Ca_MensajesError> Ca_MensajesError { get; set; }
        public DbSet<Ca_Municipios> Ca_Municipios { get; set; }
        public DbSet<CA_Opciones> CA_Opciones { get; set; }
        public DbSet<Ca_Paises> Ca_Paises { get; set; }
        public DbSet<CA_Perfiles> CA_Perfiles { get; set; }
        public DbSet<CA_Personas> CA_Personas { get; set; }
        public DbSet<CA_Usuarios> CA_Usuarios { get; set; }
        public DbSet<DE_AccionesPermisos> DE_AccionesPermisos { get; set; }
        public DbSet<DE_ArticuloClasificacion> DE_ArticuloClasificacion { get; set; }
        public DbSet<DE_Permisos> DE_Permisos { get; set; }
        public DbSet<VW_Bases> VW_Bases { get; set; }
        public DbSet<VW_Permisos> VW_Permisos { get; set; }
        public DbSet<vw_Permisos2> vw_Permisos2 { get; set; }
        public DbSet<CA_Grupos> CA_Grupos { get; set; }
        public DbSet<DE_GruposOpciones> DE_GruposOpciones { get; set; }
        public DbSet<DE_OpcionesGrupos> DE_OpcionesGrupos { get; set; }
        public DbSet<De_GrupoPerfil> De_GrupoPerfil { get; set; }
    }
}
