//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_GrupoPerfil
    {
        public short IdGrupo { get; set; }
        public byte IdPerfil { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> GET { get; set; }
        public Nullable<bool> POST { get; set; }
    }
}
