//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_OpcionesGrupos
    {
        public short IdOpcion { get; set; }
        public short IdGrupo { get; set; }
        public Nullable<short> IdOpcionGrupo { get; set; }
    
        public virtual CA_Grupos CA_Grupos { get; set; }
        public virtual CA_Opciones CA_Opciones { get; set; }
    }
}
