//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_Permisos
    {
        public DE_Permisos()
        {
            this.DE_AccionesPermisos = new HashSet<DE_AccionesPermisos>();
        }
    
        public int IdPermiso { get; set; }
        public short IdOpcion { get; set; }
        public byte IdPerfil { get; set; }
        public bool Activo { get; set; }
    
        public virtual CA_Opciones CA_Opciones { get; set; }
        public virtual CA_Perfiles CA_Perfiles { get; set; }
        public virtual ICollection<DE_AccionesPermisos> DE_AccionesPermisos { get; set; }
    }
}
