//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Permisos
    {
        public long id { get; set; }
        public Nullable<byte> IdGrupo { get; set; }
        public string Nombre { get; set; }
        public string Grupo { get; set; }
        public short IdOpcion { get; set; }
        public Nullable<short> IdOpcionP { get; set; }
        public string Controlador { get; set; }
        public string Accion { get; set; }
        public string Sistema { get; set; }
        public string DescripcionOpcion { get; set; }
        public bool Menu { get; set; }
        public short MenuPadre { get; set; }
        public Nullable<int> IdPermiso { get; set; }
        public Nullable<byte> IdPerfil { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdRegistro { get; set; }
        public Nullable<short> IdAccion { get; set; }
        public Nullable<bool> ActivoAccion { get; set; }
        public string DescripcionAccion { get; set; }
        public Nullable<byte> IdGrupoPadre { get; set; }
        public Nullable<short> IdOpcionGrupo { get; set; }
        public Nullable<bool> get { get; set; }
        public Nullable<bool> post { get; set; }
    }
}
