//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_BancosRH
    {
        public short Id_BancoRH { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Ca_BancosRH Ca_BancosRH1 { get; set; }
        public virtual Ca_BancosRH Ca_BancosRH2 { get; set; }
    }
}
