//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_Beneficiarios
    {
        public Ca_Beneficiarios()
        {
            this.CA_BeneficiariosCuentas = new HashSet<CA_BeneficiariosCuentas>();
            this.DE_BeneficiarioContactos = new HashSet<DE_BeneficiarioContactos>();
            this.De_Beneficiarios_Giros = new HashSet<De_Beneficiarios_Giros>();
            this.Ma_Polizas = new HashSet<Ma_Polizas>();
            this.De_CR_Facturas = new HashSet<De_CR_Facturas>();
            this.Ma_Compromisos = new HashSet<Ma_Compromisos>();
            this.Ma_Contrarecibos = new HashSet<Ma_Contrarecibos>();
        }
    
        public int Id_Beneficiario { get; set; }
        public int IdPersona { get; set; }
        public Nullable<byte> Id_TipoBeneficiario { get; set; }
        public Nullable<byte> Id_TipoPago { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public string Observaciones { get; set; }
        public string ClasificaProvedor { get; set; }
        public string Referencia { get; set; }
        public Nullable<byte> IdCamara { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual CA_CamaraComercio CA_CamaraComercio { get; set; }
        public virtual Ca_TipoBeneficiarios Ca_TipoBeneficiarios { get; set; }
        public virtual ICollection<CA_BeneficiariosCuentas> CA_BeneficiariosCuentas { get; set; }
        public virtual ICollection<DE_BeneficiarioContactos> DE_BeneficiarioContactos { get; set; }
        public virtual ICollection<De_Beneficiarios_Giros> De_Beneficiarios_Giros { get; set; }
        public virtual ICollection<Ma_Polizas> Ma_Polizas { get; set; }
        public virtual ICollection<De_CR_Facturas> De_CR_Facturas { get; set; }
        public virtual Ca_CuentasBancarias Ca_CuentasBancarias { get; set; }
        public virtual ICollection<Ma_Compromisos> Ma_Compromisos { get; set; }
        public virtual ICollection<Ma_Contrarecibos> Ma_Contrarecibos { get; set; }
    }
}
