//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_CuentasBancarias
    {
        public Ca_CuentasBancarias()
        {
            this.Ca_Beneficiarios = new HashSet<Ca_Beneficiarios>();
            this.De_Comprobaciones = new HashSet<De_Comprobaciones>();
            this.Ma_Polizas = new HashSet<Ma_Polizas>();
            this.Ma_ReciboIngresos = new HashSet<Ma_ReciboIngresos>();
            this.Ma_EstadosCuenta = new HashSet<Ma_EstadosCuenta>();
        }
    
        public short Id_CtaBancaria { get; set; }
        public Nullable<short> Id_Banco { get; set; }
        public string Descripcion { get; set; }
        public string NoCuenta { get; set; }
        public string Sucursal { get; set; }
        public Nullable<byte> TipoFoliador { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<int> NoChequeIni { get; set; }
        public Nullable<int> NoChequeFin { get; set; }
        public Nullable<bool> ChequePoliza { get; set; }
        public Nullable<decimal> SaldoInicial { get; set; }
        public Nullable<decimal> Depositos { get; set; }
        public Nullable<decimal> Retiros { get; set; }
        public Nullable<decimal> SaldoFinal { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<short> Id_Banco_Anterior { get; set; }
        public string Id_Cuenta_Anterior { get; set; }
        public string No_Sucursal { get; set; }
        public Nullable<bool> Exportable { get; set; }
        public string Id_Fuente { get; set; }
    
        public virtual Ca_Bancos Ca_Bancos { get; set; }
        public virtual ICollection<Ca_Beneficiarios> Ca_Beneficiarios { get; set; }
        public virtual Ca_FuentesFin Ca_FuentesFin { get; set; }
        public virtual ICollection<De_Comprobaciones> De_Comprobaciones { get; set; }
        public virtual ICollection<Ma_Polizas> Ma_Polizas { get; set; }
        public virtual ICollection<Ma_ReciboIngresos> Ma_ReciboIngresos { get; set; }
        public virtual ICollection<Ma_EstadosCuenta> Ma_EstadosCuenta { get; set; }
    }
}
