//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_Cuentas
    {
        public byte Genero { get; set; }
        public byte Grupo { get; set; }
        public byte Rubro { get; set; }
        public byte Cuenta { get; set; }
        public byte SubCuentaO1 { get; set; }
        public int SubCuentaO2 { get; set; }
        public short SubCuentaO3 { get; set; }
        public int SubCuentaO4 { get; set; }
        public string Descripcion { get; set; }
        public string Id_Cuenta { get; set; }
        public string Id_CuentaFormato { get; set; }
        public string Id_ObjetoG { get; set; }
        public string Id_Concepto { get; set; }
        public bool Nivel { get; set; }
        public Nullable<decimal> cargo01 { get; set; }
        public Nullable<decimal> cargo02 { get; set; }
        public Nullable<decimal> cargo03 { get; set; }
        public Nullable<decimal> cargo04 { get; set; }
        public Nullable<decimal> cargo05 { get; set; }
        public Nullable<decimal> cargo06 { get; set; }
        public Nullable<decimal> cargo07 { get; set; }
        public Nullable<decimal> cargo08 { get; set; }
        public Nullable<decimal> cargo09 { get; set; }
        public Nullable<decimal> cargo10 { get; set; }
        public Nullable<decimal> cargo11 { get; set; }
        public Nullable<decimal> cargo12 { get; set; }
        public Nullable<decimal> abono01 { get; set; }
        public Nullable<decimal> abono02 { get; set; }
        public Nullable<decimal> abono03 { get; set; }
        public Nullable<decimal> abono04 { get; set; }
        public Nullable<decimal> abono05 { get; set; }
        public Nullable<decimal> abono06 { get; set; }
        public Nullable<decimal> abono07 { get; set; }
        public Nullable<decimal> abono08 { get; set; }
        public Nullable<decimal> abono09 { get; set; }
        public Nullable<decimal> abono10 { get; set; }
        public Nullable<decimal> abono11 { get; set; }
        public Nullable<decimal> abono12 { get; set; }
        public Nullable<decimal> Cargo_Inicial { get; set; }
        public Nullable<decimal> Abono_Inicial { get; set; }
        public Nullable<decimal> Cargo_Final { get; set; }
        public Nullable<decimal> Abono_Final { get; set; }
        public Nullable<byte> Naturaleza { get; set; }
        public string Uso { get; set; }
        public string Observaciones { get; set; }
        public bool UNivel_Armonizado { get; set; }
        public Nullable<decimal> Porcentaje_Depreciacion { get; set; }
        public Nullable<short> Tiempo_Depreciacion { get; set; }
        public Nullable<byte> Tipo_Tiempo_Depreciacion { get; set; }
        public string Id_Cuenta_Original { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public string IdObjetoGP { get; set; }
    }
}
