//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CUR
    {
        public string Id_Concepto { get; set; }
        public string nivel4 { get; set; }
        public string nivel5 { get; set; }
        public string nivel6 { get; set; }
        public string nivel7 { get; set; }
        public string nivel8 { get; set; }
        public string nivel9 { get; set; }
        public string nivel10 { get; set; }
        public string nivel11 { get; set; }
        public string IdCUR { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> UltimoNivel { get; set; }
        public Nullable<short> uAct { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
        public string Nivel12 { get; set; }
    }
}
