//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CierreBanco
    {
        public short Id_CtaBancaria { get; set; }
        public short Id_Mes { get; set; }
        public Nullable<bool> Cerrado_Contable { get; set; }
        public Nullable<bool> Cerrado_Conciliado { get; set; }
        public Nullable<decimal> Saldo_Inicial { get; set; }
        public Nullable<decimal> Retiros { get; set; }
        public Nullable<decimal> Depositos { get; set; }
        public Nullable<decimal> Saldo_Final { get; set; }
        public Nullable<decimal> Cargos_Conciliacion { get; set; }
        public Nullable<decimal> Abonos_Conciliacion { get; set; }
        public Nullable<decimal> Saldo_Conciliado { get; set; }
        public Nullable<decimal> Saldo_EdoCta { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
