//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CamaraComercio
    {
        public CA_CamaraComercio()
        {
            this.Ca_Beneficiarios = new HashSet<Ca_Beneficiarios>();
        }
    
        public byte IdCamara { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> uAct { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual ICollection<Ca_Beneficiarios> Ca_Beneficiarios { get; set; }
    }
}
