//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_FuentesFin
    {
        public Ca_FuentesFin()
        {
            this.MA_PresupuestoEg = new HashSet<MA_PresupuestoEg>();
            this.Ca_CuentasBancarias = new HashSet<Ca_CuentasBancarias>();
            this.Ma_Contrarecibos = new HashSet<Ma_Contrarecibos>();
        }
    
        public string Id_Fuente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<bool> UltimoNivel { get; set; }
    
        public virtual ICollection<MA_PresupuestoEg> MA_PresupuestoEg { get; set; }
        public virtual ICollection<Ca_CuentasBancarias> Ca_CuentasBancarias { get; set; }
        public virtual ICollection<Ma_Contrarecibos> Ma_Contrarecibos { get; set; }
    }
}
