//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_InHabil
    {
        public short Id_Dia { get; set; }
        public Nullable<byte> Dia { get; set; }
        public Nullable<byte> Mes { get; set; }
        public string Descrip { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public System.DateTime Fecha_Act { get; set; }
    }
}
