//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_ObjetoGasto
    {
        public byte Capitulo { get; set; }
        public byte Concepto { get; set; }
        public byte PartidaGen { get; set; }
        public byte PartidaEsp { get; set; }
        public string Id_ObjetoG { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> UltimoNivel { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
