//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_TipoCompromisos
    {
        public Ca_TipoCompromisos()
        {
            this.Ma_Compromisos = new HashSet<Ma_Compromisos>();
        }
    
        public short Id_TipoCompromiso { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> UltimoComp { get; set; }
        public Nullable<bool> ImprimirFecha { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<int> Folio { get; set; }
        public Nullable<bool> Sin_Fecha { get; set; }
        public Nullable<bool> Num_Dia { get; set; }
        public Nullable<int> Num_Dias { get; set; }
        public Nullable<bool> Num_Semana { get; set; }
        public Nullable<int> Num_Semanas { get; set; }
        public Nullable<int> Dia_Semana { get; set; }
        public Nullable<bool> A_Qna { get; set; }
        public Nullable<int> Dia_Antes_Q { get; set; }
        public Nullable<int> Dia_Despues_Q { get; set; }
        public Nullable<bool> Dia_Mes { get; set; }
        public Nullable<int> Dia1 { get; set; }
        public Nullable<bool> Antes { get; set; }
        public Nullable<int> Dia2 { get; set; }
        public Nullable<bool> Despues { get; set; }
        public string Fecha_Calculada { get; set; }
        public string Pagarse { get; set; }
    
        public virtual ICollection<Ma_Compromisos> Ma_Compromisos { get; set; }
    }
}
