//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_TipoMovBancarios
    {
        public Ca_TipoMovBancarios()
        {
            this.De_Polizas = new HashSet<De_Polizas>();
        }
    
        public byte Id_TipoMovB { get; set; }
        public byte Id_FolioMovB { get; set; }
        public string Id_MovBancario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<byte> TipoMov { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual ICollection<De_Polizas> De_Polizas { get; set; }
    }
}
