//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chequestbl
    {
        public short Id_TipoPoliza { get; set; }
        public int No_Cheque { get; set; }
        public short No_Reg { get; set; }
        public string Id_Area { get; set; }
        public string Id_Funcion { get; set; }
        public string Id_Actividad { get; set; }
        public string Id_ClasificacionP { get; set; }
        public string Id_Programa { get; set; }
        public string Id_Proceso { get; set; }
        public string Id_TipoMeta { get; set; }
        public string Id_ActividadMIR { get; set; }
        public string Id_Accion { get; set; }
        public string Id_Alcance { get; set; }
        public string Id_TipoGasto { get; set; }
        public string Id_Fuente { get; set; }
        public string AnioFin { get; set; }
        public string Id_ObjetoG { get; set; }
        public string Id_Concepto { get; set; }
        public string Id_Clasifica { get; set; }
        public string Id_Cuenta { get; set; }
        public string DescripcionCta { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Importe_Letra { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<short> Id_Mov { get; set; }
        public string Beneficiario { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public Nullable<int> Id_FolioPoliza { get; set; }
        public Nullable<short> Id_MesPoliza { get; set; }
        public string No_Cuenta { get; set; }
        public string ConceptoPago { get; set; }
        public string Encabezado { get; set; }
        public short Id_TiCR { get; set; }
        public int Id_FolioCR { get; set; }
        public string Fecha_Pago_Letra { get; set; }
        public string Id_FolioPoliza_Letra { get; set; }
        public string No_Cheque_Letra { get; set; }
        public string Contrarecibo { get; set; }
        public string Compromiso { get; set; }
        public string DescCuentaB { get; set; }
        public string DescBanco { get; set; }
        public string clavePresupuestal { get; set; }
        public Nullable<System.DateTime> FechaContrarecibo { get; set; }
        public string DescPoliza { get; set; }
    }
}
