//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_Bancos
    {
        public short Id_CtaBancaria { get; set; }
        public int No_Cheque { get; set; }
        public Nullable<byte> Id_TipoPol { get; set; }
        public Nullable<int> Id_FolioPol { get; set; }
        public Nullable<byte> Id_MesPol { get; set; }
        public Nullable<int> Id_Beneficiario { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<short> Id_Estatus { get; set; }
        public string Observa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Exportado { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
