//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_BeneficiarioContactos
    {
        public int Id_Beneficiario { get; set; }
        public short IdContacto { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public string Tipo { get; set; }
    
        public virtual Ca_Beneficiarios Ca_Beneficiarios { get; set; }
    }
}
