//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Comprobaciones
    {
        public int Id_FolioGC { get; set; }
        public short Id_Consecutivo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<byte> Id_TipoPoliza { get; set; }
        public Nullable<byte> Id_MesPoliza { get; set; }
        public Nullable<int> Id_FolioPoliza { get; set; }
        public Nullable<int> Id_ReciboIng { get; set; }
        public Nullable<System.DateTime> Fecha_ReciboIng { get; set; }
        public Nullable<short> Id_CuentaBancaria { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<System.DateTime> Fecha_C { get; set; }
        public Nullable<byte> Id_TipoPoliza_C { get; set; }
        public Nullable<byte> Id_MesPoliza_C { get; set; }
        public Nullable<int> Id_FolioPoliza_C { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ma_Comprobaciones Ma_Comprobaciones { get; set; }
        public virtual Ma_Polizas Ma_Polizas { get; set; }
        public virtual Ma_Polizas Ma_Polizas1 { get; set; }
        public virtual Ca_CuentasBancarias Ca_CuentasBancarias { get; set; }
    }
}
