//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_CR_Facturas
    {
        public byte Id_TipoCR { get; set; }
        public int Id_FolioCR { get; set; }
        public int Id_Factura { get; set; }
        public int Id_Proveedor { get; set; }
        public Nullable<byte> Id_TipoDocto { get; set; }
        public string No_docto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Ret_ISR { get; set; }
        public Nullable<decimal> Ret_IVA { get; set; }
        public Nullable<decimal> Ret_Obra { get; set; }
        public Nullable<decimal> Ret_Otras { get; set; }
        public Nullable<byte> Id_Deduccion { get; set; }
        public Nullable<decimal> Otros { get; set; }
        public Nullable<byte> Id_Impuesto { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public Nullable<int> Id_Prove_ant { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ca_Beneficiarios Ca_Beneficiarios { get; set; }
        public virtual Ma_Contrarecibos Ma_Contrarecibos { get; set; }
    }
}
