//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_ContrarecibosArchivos
    {
        public int IdArchivo { get; set; }
        public byte Id_TipoCR { get; set; }
        public int Id_FolioCR { get; set; }
        public string Nombre { get; set; }
        public string NombreSistema { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<short> usu_act { get; set; }
        public string Tipo { get; set; }
    
        public virtual Ma_Contrarecibos Ma_Contrarecibos { get; set; }
    }
}
