//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Contrarecibos
    {
        public byte Id_TipoCR { get; set; }
        public int Id_FolioCR { get; set; }
        public short Id_Registro { get; set; }
        public Nullable<short> No_Comprobacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_ClavePresupuesto { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<byte> Id_Movimiento { get; set; }
        public Nullable<bool> Disponibilidad { get; set; }
        public Nullable<int> Id_FolioPoliza_Cierre { get; set; }
        public Nullable<short> Id_MesPoliza_Cierre { get; set; }
        public Nullable<short> Id_TipoCR_Cierre { get; set; }
        public Nullable<int> Id_FolioCR_Cierre { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ma_Contrarecibos Ma_Contrarecibos { get; set; }
    }
}
