//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_Evolucion
    {
        public string Id_ClavePresupuesto { get; set; }
        public byte Mes { get; set; }
        public string Id_CentroRecaudador { get; set; }
        public string Id_Fuente { get; set; }
        public string AnioFin { get; set; }
        public string Id_Alcance { get; set; }
        public string Id_Concepto { get; set; }
        public Nullable<decimal> Estimado { get; set; }
        public Nullable<decimal> Ampliaciones { get; set; }
        public Nullable<decimal> Reducciones { get; set; }
        public Nullable<decimal> Modificado { get; set; }
        public Nullable<decimal> Devengado { get; set; }
        public Nullable<decimal> Recaudado { get; set; }
        public Nullable<decimal> PorEjecutar { get; set; }
    }
}
