//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Polizas
    {
        public byte Id_TipoPoliza { get; set; }
        public int Id_FolioPoliza { get; set; }
        public byte Id_MesPoliza { get; set; }
        public short Id_Registro { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Id_ClavePresupuesto { get; set; }
        public string Id_ClavePresupuestoIng { get; set; }
        public string IdCur { get; set; }
        public string DescripcionMP { get; set; }
        public Nullable<byte> Id_Movimiento { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<byte> Estatus { get; set; }
        public Nullable<byte> Id_TipoMovB { get; set; }
        public Nullable<byte> Id_FolioMovB { get; set; }
        public Nullable<bool> TransferidoC { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ca_TipoMovBancarios Ca_TipoMovBancarios { get; set; }
        public virtual Ma_Polizas Ma_Polizas { get; set; }
    }
}
