//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_ReciboIngresos
    {
        public int Folio { get; set; }
        public byte IdRegistro { get; set; }
        public string Id_ClavePresupuestoIng { get; set; }
        public string IdCur { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<byte> Id_Movimiento { get; set; }
        public Nullable<short> uAct { get; set; }
        public Nullable<System.DateTime> fAct { get; set; }
    
        public virtual Ma_ReciboIngresos Ma_ReciboIngresos { get; set; }
    }
}
