//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_ReferenciasPolizas
    {
        public byte IdTipoPoliza { get; set; }
        public int IdFolioPoliza { get; set; }
        public byte IdMesPoliza { get; set; }
        public Nullable<byte> IdTipoPCom { get; set; }
        public Nullable<int> IdFolioPCom { get; set; }
        public Nullable<byte> IdMesPCom { get; set; }
        public Nullable<byte> IdTipoPComC { get; set; }
        public Nullable<int> IdFolioPComC { get; set; }
        public Nullable<byte> IdMesPComC { get; set; }
        public Nullable<byte> IdTipoPDev { get; set; }
        public Nullable<int> IdFolioPDev { get; set; }
        public Nullable<byte> IdMesPDev { get; set; }
        public Nullable<byte> IdTipoPDevC { get; set; }
        public Nullable<int> IdFolioPDevC { get; set; }
        public Nullable<byte> IdMesPDevC { get; set; }
        public Nullable<byte> IdTipoPEje { get; set; }
        public Nullable<int> IdFolioPEje { get; set; }
        public Nullable<byte> IdMesPEje { get; set; }
        public Nullable<byte> IdTipoPEjeC { get; set; }
        public Nullable<int> IdFolioPEjeC { get; set; }
        public Nullable<byte> IdMesPEjeC { get; set; }
        public Nullable<byte> IdTipoPPag { get; set; }
        public Nullable<int> IdFolioPPag { get; set; }
        public Nullable<byte> IdMesPPag { get; set; }
        public Nullable<byte> IdTipoPPagC { get; set; }
        public Nullable<int> IdFolioPPagC { get; set; }
        public Nullable<byte> IdMesPPagC { get; set; }
        public Nullable<byte> IdTipoPDevI { get; set; }
        public Nullable<int> IdFolioPDevI { get; set; }
        public Nullable<byte> IdMesPDevI { get; set; }
        public Nullable<byte> IdTipoPDevIC { get; set; }
        public Nullable<int> IdFolioPDevIC { get; set; }
        public Nullable<byte> IdMesPDevIC { get; set; }
        public Nullable<byte> IdTipoPRec { get; set; }
        public Nullable<int> IdFolioPRec { get; set; }
        public Nullable<byte> IdMesPRec { get; set; }
        public Nullable<byte> IdTipoPRecC { get; set; }
        public Nullable<int> IdFolioPRecC { get; set; }
        public Nullable<byte> IdMesPRecC { get; set; }
        public Nullable<byte> IdTipoPolizaDC { get; set; }
        public Nullable<int> IdFolioPolizaDC { get; set; }
        public Nullable<byte> IdMesPolizaDC { get; set; }
    
        public virtual Ma_Polizas Ma_Polizas { get; set; }
        public virtual Ma_Polizas Ma_Polizas1 { get; set; }
        public virtual Ma_Polizas Ma_Polizas2 { get; set; }
        public virtual Ma_Polizas Ma_Polizas3 { get; set; }
        public virtual Ma_Polizas Ma_Polizas4 { get; set; }
        public virtual Ma_Polizas Ma_Polizas5 { get; set; }
        public virtual Ma_Polizas Ma_Polizas6 { get; set; }
        public virtual Ma_Polizas Ma_Polizas7 { get; set; }
        public virtual Ma_Polizas Ma_Polizas8 { get; set; }
        public virtual Ma_Polizas Ma_Polizas9 { get; set; }
        public virtual Ma_Polizas Ma_Polizas10 { get; set; }
        public virtual Ma_Polizas Ma_Polizas11 { get; set; }
        public virtual Ma_Polizas Ma_Polizas12 { get; set; }
        public virtual Ma_Polizas Ma_Polizas13 { get; set; }
    }
}
