//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_Transferencia
    {
        public int Id_Transferencia { get; set; }
        public short Id_Consecutivo { get; set; }
        public Nullable<short> Id_Movimiento { get; set; }
        public string Id_ClavePresupuesto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Pre01 { get; set; }
        public Nullable<decimal> Pre02 { get; set; }
        public Nullable<decimal> Pre03 { get; set; }
        public Nullable<decimal> Pre04 { get; set; }
        public Nullable<decimal> Pre05 { get; set; }
        public Nullable<decimal> Pre06 { get; set; }
        public Nullable<decimal> Pre07 { get; set; }
        public Nullable<decimal> Pre08 { get; set; }
        public Nullable<decimal> Pre09 { get; set; }
        public Nullable<decimal> Pre10 { get; set; }
        public Nullable<decimal> Pre11 { get; set; }
        public Nullable<decimal> Pre12 { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    }
}
