//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class De_TransferenciaIng
    {
        public int Folio { get; set; }
        public byte IdRegistro { get; set; }
        public Nullable<short> Id_Movimiento { get; set; }
        public string Id_ClavePresupuestoIng { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Est01 { get; set; }
        public Nullable<decimal> Est02 { get; set; }
        public Nullable<decimal> Est03 { get; set; }
        public Nullable<decimal> Est04 { get; set; }
        public Nullable<decimal> Est05 { get; set; }
        public Nullable<decimal> Est06 { get; set; }
        public Nullable<decimal> Est07 { get; set; }
        public Nullable<decimal> Est08 { get; set; }
        public Nullable<decimal> Est09 { get; set; }
        public Nullable<decimal> Est10 { get; set; }
        public Nullable<decimal> Est11 { get; set; }
        public Nullable<decimal> Est12 { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ma_TransferenciasIng Ma_TransferenciasIng { get; set; }
    }
}
