//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_Contrarecibos
    {
        public Ma_Contrarecibos()
        {
            this.De_Contrarecibos = new HashSet<De_Contrarecibos>();
            this.DE_ContrarecibosArchivos = new HashSet<DE_ContrarecibosArchivos>();
            this.De_CR_Facturas = new HashSet<De_CR_Facturas>();
            this.Ma_Compromisos = new HashSet<Ma_Compromisos>();
            this.Ma_Polizas = new HashSet<Ma_Polizas>();
        }
    
        public byte Id_TipoCR { get; set; }
        public int Id_FolioCR { get; set; }
        public Nullable<System.DateTime> FechaCR { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaVen { get; set; }
        public Nullable<int> Id_Beneficiario { get; set; }
        public Nullable<int> Id_FolioPolizaCR { get; set; }
        public Nullable<byte> Id_MesPolizaCR { get; set; }
        public Nullable<int> Id_FolioPolizaCR_C { get; set; }
        public Nullable<byte> Id_MesPolizaCR_C { get; set; }
        public Nullable<System.DateTime> FechaCancelacionCR { get; set; }
        public string Usu_CR { get; set; }
        public Nullable<bool> Impreso_CR { get; set; }
        public Nullable<int> Id_FolioPolizaCH { get; set; }
        public Nullable<byte> Id_MesPolizaCH { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Usu_Pago { get; set; }
        public Nullable<byte> Id_EstatusCR { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<bool> Impreso_CH { get; set; }
        public Nullable<short> Id_TipoCompromiso { get; set; }
        public Nullable<int> Id_FolioPolizaCH_C { get; set; }
        public Nullable<byte> Id_MesPolizaCH_C { get; set; }
        public Nullable<System.DateTime> FechaCancelacion_CH { get; set; }
        public string Id_CuentaFR { get; set; }
        public string Id_CuentaBeneficiario { get; set; }
        public Nullable<System.DateTime> FechaCierreGC { get; set; }
        public Nullable<byte> Estatus_GC { get; set; }
        public Nullable<int> Id_FolioGC { get; set; }
        public Nullable<bool> Ejercicio_Anterior { get; set; }
        public Nullable<bool> AmpliacionFR { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<byte> Id_MesPO_Ejercido { get; set; }
        public Nullable<int> Id_FolioPO_Ejercido { get; set; }
        public Nullable<byte> Id_MesPO_Ejercido_C { get; set; }
        public Nullable<int> Id_FolioPO_Ejercido_C { get; set; }
        public Nullable<byte> Id_MesPO_Pagado { get; set; }
        public Nullable<int> Id_FolioPO_Pagado { get; set; }
        public Nullable<byte> Id_MesPO_Pagado_C { get; set; }
        public Nullable<int> Id_FolioPO_Pagado_C { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaEjercido { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaPagado { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public string Spei { get; set; }
        public string Id_Fuente { get; set; }
        public Nullable<int> IdPersona_ENP { get; set; }
        public Nullable<byte> Id_TipoMovimiento_AH { get; set; }
        public string Id_Cuenta_AH { get; set; }
        public Nullable<decimal> Importe_AH { get; set; }
        public string Id_Cuenta_AH2 { get; set; }
        public Nullable<byte> Id_TipoMovimiento_AH2 { get; set; }
        public Nullable<decimal> Importe_AH2 { get; set; }
        public string Id_Cuenta_AH3 { get; set; }
        public Nullable<byte> Id_TipoMovimiento_AH3 { get; set; }
        public Nullable<decimal> Importe_AH3 { get; set; }
        public string Id_Cuenta_AH4 { get; set; }
        public Nullable<byte> Id_TipoMovimiento_AH4 { get; set; }
        public Nullable<decimal> Importe_AH4 { get; set; }
        public Nullable<decimal> Importe_CH { get; set; }
    
        public virtual Ca_Beneficiarios Ca_Beneficiarios { get; set; }
        public virtual Ca_FuentesFin Ca_FuentesFin { get; set; }
        public virtual Ca_TipoContrarecibos Ca_TipoContrarecibos { get; set; }
        public virtual ICollection<De_Contrarecibos> De_Contrarecibos { get; set; }
        public virtual ICollection<DE_ContrarecibosArchivos> DE_ContrarecibosArchivos { get; set; }
        public virtual ICollection<De_CR_Facturas> De_CR_Facturas { get; set; }
        public virtual Ma_Comprobaciones Ma_Comprobaciones { get; set; }
        public virtual ICollection<Ma_Compromisos> Ma_Compromisos { get; set; }
        public virtual Ma_Contrarecibos Ma_Contrarecibos1 { get; set; }
        public virtual Ma_Contrarecibos Ma_Contrarecibos2 { get; set; }
        public virtual ICollection<Ma_Polizas> Ma_Polizas { get; set; }
    }
}
