//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_Compromisos
    {
        public Ma_Compromisos()
        {
            this.De_Compromisos = new HashSet<De_Compromisos>();
        }
    
        public short Id_TipoCompromiso { get; set; }
        public int Id_FolioCompromiso { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Usuario_Orden { get; set; }
        public Nullable<System.DateTime> Fecha_Orden { get; set; }
        public Nullable<int> Id_Beneficiario { get; set; }
        public string Id_Cuenta_Beneficiario { get; set; }
        public Nullable<int> No_Requisicion { get; set; }
        public Nullable<System.DateTime> Fecha_Requisicion { get; set; }
        public Nullable<int> No_Adquisicion { get; set; }
        public Nullable<System.DateTime> Fecha_Adquisicion { get; set; }
        public string Usuario_Autorizo { get; set; }
        public Nullable<System.DateTime> Fecha_Autorizo { get; set; }
        public string Observaciones { get; set; }
        public string Usuario_Cancela { get; set; }
        public Nullable<System.DateTime> Fecha_Cancela { get; set; }
        public string Usuario_Recibe_Area { get; set; }
        public Nullable<System.DateTime> Fecha_Recibe_Area { get; set; }
        public string Observa_Recibio { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<byte> Id_TipoCR { get; set; }
        public Nullable<int> Id_FolioCR { get; set; }
        public Nullable<byte> Id_TipoPoliza { get; set; }
        public Nullable<byte> Id_MesPoliza { get; set; }
        public Nullable<int> Id_FolioPoliza { get; set; }
        public Nullable<byte> Id_MesPoliza_C { get; set; }
        public Nullable<int> Id_FolioPoliza_C { get; set; }
        public Nullable<short> Estatus { get; set; }
        public Nullable<byte> Id_MesPO_Comprometido { get; set; }
        public Nullable<int> Id_FolioPO_Comprometido { get; set; }
        public Nullable<byte> Id_MesPO_Comprometido_C { get; set; }
        public Nullable<int> Id_FolioPO_Comprometido_C { get; set; }
        public Nullable<byte> Id_MesPO_Devengado { get; set; }
        public Nullable<int> Id_FolioPO_Devengado { get; set; }
        public Nullable<byte> Id_MesPO_Devengado_C { get; set; }
        public Nullable<int> Id_FolioPO_Devengado_C { get; set; }
        public Nullable<bool> Historial { get; set; }
        public string TipoNomina { get; set; }
        public Nullable<byte> No_Quincena { get; set; }
        public Nullable<byte> Mes_Quincena { get; set; }
        public string No_Nomina { get; set; }
        public Nullable<System.DateTime> Fecha_Devengado { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaCompro { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaDevengo { get; set; }
        public Nullable<bool> Adquisicion { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual Ca_Beneficiarios Ca_Beneficiarios { get; set; }
        public virtual Ca_TipoCompromisos Ca_TipoCompromisos { get; set; }
        public virtual ICollection<De_Compromisos> De_Compromisos { get; set; }
        public virtual Ma_Polizas Ma_Polizas { get; set; }
        public virtual Ma_Contrarecibos Ma_Contrarecibos { get; set; }
    }
}
