//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_EstadosCuenta
    {
        public int IdRegistro { get; set; }
        public Nullable<short> Id_CuentaBancaria { get; set; }
        public string No_CuentaBancaria { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Sucursal { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<decimal> Saldos { get; set; }
        public string Referencia { get; set; }
        public string Concepto { get; set; }
        public Nullable<bool> Conciliado { get; set; }
        public Nullable<byte> IdMes { get; set; }
    
        public virtual Ca_CuentasBancarias Ca_CuentasBancarias { get; set; }
    }
}
