//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_MovimientosConciliacion
    {
        public short Id_CtaBancaria { get; set; }
        public string NoCuenta { get; set; }
        public short Id_Mes { get; set; }
        public short No_Registro { get; set; }
        public string Id_CuentaContable { get; set; }
        public Nullable<short> Id_TipoMovimientoBancario { get; set; }
        public Nullable<short> Id_FolioMovimienotBancario { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public string Referencia { get; set; }
        public Nullable<short> Id_Movimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<short> Estatus { get; set; }
        public string EstadoCuenta { get; set; }
        public Nullable<short> Origen { get; set; }
        public Nullable<short> Id_TipoMovimiento_Original { get; set; }
        public Nullable<short> Id_FolioMovimiento_Original { get; set; }
        public Nullable<byte> Id_TipoPoliza { get; set; }
        public Nullable<int> Id_FolioPoliza { get; set; }
        public Nullable<byte> Id_MesPoliza { get; set; }
        public Nullable<short> No_RegistroPoliza { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<bool> Capturado { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Conciliacion { get; set; }
    }
}
