//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_Nomina
    {
        public string No_Control { get; set; }
        public string Tipo_Nomina { get; set; }
        public string No_Nomina { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string CURP { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Pat { get; set; }
        public string Apellido_Mat { get; set; }
        public Nullable<int> Id_Banco_RH { get; set; }
        public string No_Tarjeta { get; set; }
        public string Tipo_Pago { get; set; }
        public Nullable<decimal> Neto { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<int> Id_FolioPolE { get; set; }
        public Nullable<byte> Id_MesPolE { get; set; }
        public Nullable<short> Id_Banco { get; set; }
        public Nullable<int> Id_ctaBancaria { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<bool> Asignado { get; set; }
        public Nullable<byte> Quincena { get; set; }
    }
}
