//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_Polizas
    {
        public Ma_Polizas()
        {
            this.De_Comprobaciones = new HashSet<De_Comprobaciones>();
            this.De_Comprobaciones1 = new HashSet<De_Comprobaciones>();
            this.De_Polizas = new HashSet<De_Polizas>();
            this.De_ReferenciasPolizas1 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas2 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas3 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas4 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas5 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas6 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas7 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas8 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas9 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas10 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas11 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas12 = new HashSet<De_ReferenciasPolizas>();
            this.De_ReferenciasPolizas13 = new HashSet<De_ReferenciasPolizas>();
            this.Ma_ReciboIngresos = new HashSet<Ma_ReciboIngresos>();
            this.Ma_ReciboIngresos1 = new HashSet<Ma_ReciboIngresos>();
            this.Ma_ReciboIngresos2 = new HashSet<Ma_ReciboIngresos>();
            this.Ma_ReciboIngresos3 = new HashSet<Ma_ReciboIngresos>();
            this.Ma_Compromisos = new HashSet<Ma_Compromisos>();
        }
    
        public byte Id_TipoPoliza { get; set; }
        public int Id_FolioPoliza { get; set; }
        public byte Id_MesPoliza { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<int> Id_Beneficiario { get; set; }
        public Nullable<byte> Id_TipoCR { get; set; }
        public Nullable<int> Id_FolioCR { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<byte> Estatus { get; set; }
        public Nullable<byte> Id_ClasPoliza { get; set; }
        public Nullable<byte> Id_SubClasificaPol { get; set; }
        public string Recibi_Donativo { get; set; }
        public Nullable<int> Id_Folio_Donativo { get; set; }
        public string RFC_Donativo { get; set; }
        public Nullable<short> Tipo_Donativo { get; set; }
        public string Facturas { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<short> Id_TipoCompromiso { get; set; }
        public Nullable<int> Id_FolioCompromiso { get; set; }
    
        public virtual Ca_Beneficiarios Ca_Beneficiarios { get; set; }
        public virtual Ca_ClasificaPolizas Ca_ClasificaPolizas { get; set; }
        public virtual Ca_TipoPolizas Ca_TipoPolizas { get; set; }
        public virtual ICollection<De_Comprobaciones> De_Comprobaciones { get; set; }
        public virtual ICollection<De_Comprobaciones> De_Comprobaciones1 { get; set; }
        public virtual ICollection<De_Polizas> De_Polizas { get; set; }
        public virtual De_ReferenciasPolizas De_ReferenciasPolizas { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas1 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas2 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas3 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas4 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas5 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas6 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas7 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas8 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas9 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas10 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas11 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas12 { get; set; }
        public virtual ICollection<De_ReferenciasPolizas> De_ReferenciasPolizas13 { get; set; }
        public virtual ICollection<Ma_ReciboIngresos> Ma_ReciboIngresos { get; set; }
        public virtual ICollection<Ma_ReciboIngresos> Ma_ReciboIngresos1 { get; set; }
        public virtual ICollection<Ma_ReciboIngresos> Ma_ReciboIngresos2 { get; set; }
        public virtual ICollection<Ma_ReciboIngresos> Ma_ReciboIngresos3 { get; set; }
        public virtual Ca_CuentasBancarias Ca_CuentasBancarias { get; set; }
        public virtual ICollection<Ma_Compromisos> Ma_Compromisos { get; set; }
        public virtual Ma_Contrarecibos Ma_Contrarecibos { get; set; }
    }
}
