//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_PreComprometido
    {
        public int Folio { get; set; }
        public string IdClavepresupuesto { get; set; }
        public byte Mes { get; set; }
        public int NoAdquisiciones { get; set; }
        public Nullable<byte> tipoCompra { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Usuario { get; set; }
        public Nullable<int> IdProvedor { get; set; }
        public Nullable<System.DateTime> FechaPrecompromiso { get; set; }
    }
}
