//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_PresupuestoEg
    {
        public string Id_Area { get; set; }
        public string Id_Funcion { get; set; }
        public string Id_Actividad { get; set; }
        public string Id_ClasificacionP { get; set; }
        public string Id_Programa { get; set; }
        public string Id_Proceso { get; set; }
        public string Id_TipoMeta { get; set; }
        public string Id_ActividadMIR { get; set; }
        public string Id_Accion { get; set; }
        public string Id_Alcance { get; set; }
        public string Id_TipoG { get; set; }
        public string Id_Fuente { get; set; }
        public string AnioFin { get; set; }
        public string Id_ObjetoG { get; set; }
        public string Id_ClavePresupuesto { get; set; }
        public Nullable<decimal> Aprobado01 { get; set; }
        public Nullable<decimal> Aprobado02 { get; set; }
        public Nullable<decimal> Aprobado03 { get; set; }
        public Nullable<decimal> Aprobado04 { get; set; }
        public Nullable<decimal> Aprobado05 { get; set; }
        public Nullable<decimal> Aprobado06 { get; set; }
        public Nullable<decimal> Aprobado07 { get; set; }
        public Nullable<decimal> Aprobado08 { get; set; }
        public Nullable<decimal> Aprobado09 { get; set; }
        public Nullable<decimal> Aprobado10 { get; set; }
        public Nullable<decimal> Aprobado11 { get; set; }
        public Nullable<decimal> Aprobado12 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<byte> Id_MesPO_Aprobado { get; set; }
        public Nullable<int> Id_FolioPO_Aprobado { get; set; }
        public Nullable<byte> Id_MesPO_Aprobado_C { get; set; }
        public Nullable<int> Id_FolioPO_Aprobado_C { get; set; }
        public Nullable<System.DateTime> Fecha_Aprobado { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaAprobado { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_act { get; set; }
    
        public virtual Ca_ActividadesInst Ca_ActividadesInst { get; set; }
        public virtual Ca_AlcanceGeo Ca_AlcanceGeo { get; set; }
        public virtual Ca_ClasProgramatica Ca_ClasProgramatica { get; set; }
        public virtual Ca_FuentesFin Ca_FuentesFin { get; set; }
        public virtual CA_Programas CA_Programas { get; set; }
        public virtual Ca_Proyecto Ca_Proyecto { get; set; }
        public virtual Ca_TipoGastos Ca_TipoGastos { get; set; }
        public virtual Ca_TipoMeta Ca_TipoMeta { get; set; }
    }
}
