//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ma_TransferenciasIng
    {
        public Ma_TransferenciasIng()
        {
            this.De_TransferenciaIng = new HashSet<De_TransferenciaIng>();
        }
    
        public int Folio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descrip { get; set; }
        public Nullable<byte> Id_Mes { get; set; }
        public Nullable<byte> Id_Mes_Origen { get; set; }
        public Nullable<short> Id_Usuario { get; set; }
        public Nullable<decimal> Importe_AMP { get; set; }
        public Nullable<decimal> Importe_RED { get; set; }
        public Nullable<byte> Id_TipoT { get; set; }
        public Nullable<byte> Id_Estatus { get; set; }
        public Nullable<System.DateTime> Fecha_Afecta { get; set; }
        public string DescripAjuste { get; set; }
        public Nullable<decimal> Importe_AmpAjuste { get; set; }
        public Nullable<decimal> Importe_RedAjuste { get; set; }
        public string Id_Area { get; set; }
        public Nullable<System.DateTime> Fecha_Reporte { get; set; }
        public string Id_Clasifica { get; set; }
        public string Id_CRIInicial { get; set; }
        public string Id_CRIFinal { get; set; }
        public Nullable<bool> Id_PptoModificado { get; set; }
        public Nullable<byte> Id_MesPO_Modificado { get; set; }
        public Nullable<int> Id_FolioPO_Modificado { get; set; }
        public Nullable<byte> Id_MesPO_Modificado_Cancela { get; set; }
        public Nullable<int> Id_FolioPO_Modificado_Cancela { get; set; }
        public Nullable<decimal> Importe_Requerido { get; set; }
        public Nullable<decimal> Importe_A_Cubrir { get; set; }
        public Nullable<bool> Alterado { get; set; }
        public Nullable<short> Usu_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
    
        public virtual ICollection<De_TransferenciaIng> De_TransferenciaIng { get; set; }
    }
}
