//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDisponibilidadAnual
    {
        public string Id_ClavePresupuesto { get; set; }
        public Nullable<decimal> Aprobado { get; set; }
        public Nullable<decimal> Ampliaciones1 { get; set; }
        public Nullable<decimal> Reducciones1 { get; set; }
        public Nullable<decimal> Ampliaciones { get; set; }
        public Nullable<decimal> Reducciones { get; set; }
        public Nullable<decimal> Vigente { get; set; }
        public Nullable<decimal> PreComprometido { get; set; }
        public Nullable<decimal> Comprometido { get; set; }
        public Nullable<decimal> Devengado { get; set; }
        public Nullable<decimal> Ejercido { get; set; }
        public Nullable<decimal> Pagado { get; set; }
        public Nullable<decimal> Disponible { get; set; }
    }
}
