//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEjercido_MovimientosPolizas
    {
        public byte Id_TipoPoliza { get; set; }
        public int Id_FolioPoliza { get; set; }
        public byte Id_MesPoliza { get; set; }
        public short Id_Registro { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<byte> Id_TipoCR { get; set; }
        public Nullable<int> Id_FolioCR { get; set; }
        public Nullable<byte> Id_Movimiento { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Id_Area { get; set; }
        public string Id_Funcion { get; set; }
        public string Id_Actividad { get; set; }
        public string Id_ClasificacionP { get; set; }
        public string Id_Programa { get; set; }
        public string Id_Proceso { get; set; }
        public string Id_TipoMeta { get; set; }
        public string Id_ActividadMIR { get; set; }
        public string Id_Accion { get; set; }
        public string Id_Fuente { get; set; }
        public string AnioFin { get; set; }
        public string Id_ObjetoG { get; set; }
        public string Id_TipoG { get; set; }
        public string Id_Alcance { get; set; }
        public Nullable<byte> Id_EstatusCR { get; set; }
        public Nullable<int> MesCR { get; set; }
        public string Id_ClavePresupuesto { get; set; }
    }
}
