//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vListaChequesImpresionNomina
    {
        public string No_Nomina { get; set; }
        public string Tipo_Nomina { get; set; }
        public string No_Control { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Id_ctaBancaria { get; set; }
        public string NoCuenta { get; set; }
        public string ConceptoPago { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
    }
}
