//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVerificaPoliza
    {
        public string TipoPol { get; set; }
        public byte Id_TipoPoliza { get; set; }
        public int Id_FolioPoliza { get; set; }
        public byte Id_MesPoliza { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
        public Nullable<int> Id_Cuenta { get; set; }
        public Nullable<int> Id_Area { get; set; }
        public Nullable<int> Id_Funcion { get; set; }
        public Nullable<int> Id_Actividad { get; set; }
        public Nullable<int> id_clasificacionP { get; set; }
        public Nullable<int> Id_Programa { get; set; }
        public Nullable<int> Id_Proceso { get; set; }
        public Nullable<int> Id_TipoMeta { get; set; }
        public Nullable<int> Id_ActividadMIR { get; set; }
        public Nullable<int> Id_Accion { get; set; }
        public Nullable<int> Id_Alcance { get; set; }
        public Nullable<int> Id_TipoG { get; set; }
        public Nullable<int> Id_Fuente { get; set; }
        public Nullable<int> anioFin { get; set; }
        public Nullable<int> Id_ObjetoG { get; set; }
        public Nullable<int> Id_Concepto { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
    }
}
