//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Beneficiarios
    {
        public int Id_Beneficiario { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Id_ClasificaBene { get; set; }
        public string Clasificacion { get; set; }
        public string Id_Cuenta { get; set; }
        public string Id_CuentaFormato { get; set; }
    }
}
