//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Contrarecibos
    {
        public byte Id_TipoCR { get; set; }
        public int Id_FolioCR { get; set; }
        public Nullable<System.DateTime> FechaCR { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaVen { get; set; }
        public Nullable<int> Id_Beneficiario { get; set; }
        public Nullable<int> Id_FolioPolizaCR { get; set; }
        public Nullable<byte> Id_MesPolizaCR { get; set; }
        public Nullable<int> Id_FolioPolizaCR_C { get; set; }
        public Nullable<byte> Id_MesPolizaCR_C { get; set; }
        public Nullable<System.DateTime> FechaCancelacionCR { get; set; }
        public string Usu_CR { get; set; }
        public Nullable<bool> Impreso_CR { get; set; }
        public Nullable<int> Id_FolioPolizaCH { get; set; }
        public Nullable<byte> Id_MesPolizaCH { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Usu_Pago { get; set; }
        public Nullable<byte> Id_EstatusCR { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public Nullable<bool> Impreso_CH { get; set; }
        public Nullable<short> Id_TipoCompromiso { get; set; }
        public Nullable<int> Id_FolioPolizaCH_C { get; set; }
        public Nullable<byte> Id_MesPolizaCH_C { get; set; }
        public Nullable<System.DateTime> FechaCancelacion_CH { get; set; }
        public string Id_CuentaFR { get; set; }
        public string Id_CuentaBeneficiario { get; set; }
        public Nullable<System.DateTime> FechaCierreGC { get; set; }
        public Nullable<byte> Estatus_GC { get; set; }
        public Nullable<int> Id_FolioGC { get; set; }
        public Nullable<bool> Ejercicio_Anterior { get; set; }
        public Nullable<bool> AmpliacionFR { get; set; }
        public Nullable<short> Usuario_Act { get; set; }
        public Nullable<System.DateTime> Fecha_Act { get; set; }
        public Nullable<byte> Id_MesPO_Ejercido { get; set; }
        public Nullable<int> Id_FolioPO_Ejercido { get; set; }
        public Nullable<byte> Id_MesPO_Ejercido_C { get; set; }
        public Nullable<int> Id_FolioPO_Ejercido_C { get; set; }
        public Nullable<byte> Id_MesPO_Pagado { get; set; }
        public Nullable<int> Id_FolioPO_Pagado { get; set; }
        public Nullable<byte> Id_MesPO_Pagado_C { get; set; }
        public Nullable<int> Id_FolioPO_Pagado_C { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaEjercido { get; set; }
        public Nullable<System.DateTime> Fecha_CancelaPagado { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public string Spei { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Id_FolioCompromiso { get; set; }
        public Nullable<int> No_Requisicion { get; set; }
        public Nullable<int> No_Adquisicion { get; set; }
    }
}
