//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Conciliacion
    {
        public string Tipo { get; set; }
        public string Movimiento { get; set; }
        public Nullable<int> No_Cheque { get; set; }
        public Nullable<decimal> Cargos { get; set; }
        public Nullable<decimal> Abonos { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Referencia { get; set; }
        public short Id_CtaBancaria { get; set; }
        public short Id_Mes { get; set; }
        public string NoCuenta { get; set; }
        public short No_Registro { get; set; }
        public byte Id_TipoMovB { get; set; }
        public byte Id_FolioMovB { get; set; }
    }
}
