//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CuentasConPadres
    {
        public Nullable<long> Id { get; set; }
        public long Padre { get; set; }
        public string Id_CuentaFormato { get; set; }
        public Nullable<decimal> cargo01 { get; set; }
        public Nullable<decimal> cargo02 { get; set; }
        public Nullable<decimal> cargo03 { get; set; }
        public Nullable<decimal> cargo04 { get; set; }
        public Nullable<decimal> cargo05 { get; set; }
        public Nullable<decimal> cargo06 { get; set; }
        public Nullable<decimal> cargo07 { get; set; }
        public Nullable<decimal> cargo08 { get; set; }
        public Nullable<decimal> cargo09 { get; set; }
        public Nullable<decimal> cargo10 { get; set; }
        public Nullable<decimal> cargo11 { get; set; }
        public Nullable<decimal> cargo12 { get; set; }
        public Nullable<decimal> abono01 { get; set; }
        public Nullable<decimal> abono02 { get; set; }
        public Nullable<decimal> abono03 { get; set; }
        public Nullable<decimal> abono04 { get; set; }
        public Nullable<decimal> abono05 { get; set; }
        public Nullable<decimal> abono06 { get; set; }
        public Nullable<decimal> abono07 { get; set; }
        public Nullable<decimal> abono08 { get; set; }
        public Nullable<decimal> abono09 { get; set; }
        public Nullable<decimal> abono10 { get; set; }
        public Nullable<decimal> abono11 { get; set; }
        public Nullable<decimal> abono12 { get; set; }
        public Nullable<decimal> Cargo_Inicial { get; set; }
        public Nullable<decimal> Abono_Inicial { get; set; }
        public bool Nivel { get; set; }
    }
}
