//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DisponibilidadMeses
    {
        public string Id_ClavePresupuesto { get; set; }
        public Nullable<decimal> Disponible01 { get; set; }
        public Nullable<decimal> Disponible02 { get; set; }
        public Nullable<decimal> Disponible03 { get; set; }
        public Nullable<decimal> Disponible04 { get; set; }
        public Nullable<decimal> Disponible05 { get; set; }
        public Nullable<decimal> Disponible06 { get; set; }
        public Nullable<decimal> Disponible07 { get; set; }
        public Nullable<decimal> Disponible08 { get; set; }
        public Nullable<decimal> Disponible09 { get; set; }
        public Nullable<decimal> Disponible10 { get; set; }
        public Nullable<decimal> Disponible11 { get; set; }
        public Nullable<decimal> Disponible12 { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
