//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesoreriaVS12.Areas.Tesoreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DetalleReciboIng
    {
        public int Folio { get; set; }
        public byte IdRegistro { get; set; }
        public string Id_ClavePresupuestoIng { get; set; }
        public string Id_CentroRecaudador { get; set; }
        public string Id_Fuente { get; set; }
        public string AnioFin { get; set; }
        public string Id_Alcance { get; set; }
        public string Id_Concepto { get; set; }
        public string CRI { get; set; }
        public string IdCur { get; set; }
        public string CUR { get; set; }
        public Nullable<System.DateTime> FechaRecaudacion { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Id_Cuenta { get; set; }
        public Nullable<byte> Id_Movimiento { get; set; }
        public int IdContribuyente { get; set; }
        public string NombreContribuyente { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<short> Id_CtaBancaria { get; set; }
        public string CuentaBancaria { get; set; }
        public byte Id_CajaR { get; set; }
        public string CajaReceptora { get; set; }
        public Nullable<byte> IdEstatus { get; set; }
    }
}
