//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TesoreriaVS12.EnviaCorreo
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Configuration;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Envio de CorreosBinding", Namespace="http://www.colima-estado.gob.mx/kioscos/tramitesyservicios/wscorreos/wscorreos.ph" +
        "p")]
    public partial class EnviodeCorreos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Envia_MailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EnviodeCorreos() {
            this.Url = ConfigurationManager.AppSettings.Get("WebServiceCorreo"); ;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Envia_MailCompletedEventHandler Envia_MailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("uri:Service/Envia_Mail", RequestNamespace="uri:Service", ResponseNamespace="uri:Service")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string Envia_Mail(string correo, string titulo, string mensaje, string destinatario) {
            object[] results = this.Invoke("Envia_Mail", new object[] {
                        correo,
                        titulo,
                        mensaje,
                        destinatario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Envia_MailAsync(string correo, string titulo, string mensaje, string destinatario) {
            this.Envia_MailAsync(correo, titulo, mensaje, destinatario, null);
        }
        
        /// <remarks/>
        public void Envia_MailAsync(string correo, string titulo, string mensaje, string destinatario, object userState) {
            if ((this.Envia_MailOperationCompleted == null)) {
                this.Envia_MailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnvia_MailOperationCompleted);
            }
            this.InvokeAsync("Envia_Mail", new object[] {
                        correo,
                        titulo,
                        mensaje,
                        destinatario}, this.Envia_MailOperationCompleted, userState);
        }
        
        private void OnEnvia_MailOperationCompleted(object arg) {
            if ((this.Envia_MailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Envia_MailCompleted(this, new Envia_MailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Envia_MailCompletedEventHandler(object sender, Envia_MailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Envia_MailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Envia_MailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591